### ISSUE TITLE
无法获取账单数据

### ISSUE THREAD

**Issue by timelyRain666** [C3H3-AI/ha-crcgas#7]
<img width="1200" height="1875" alt="Image" src="https://github.com/user-attachments/assets/70dc05b8-1d15-4d7c-80a4-520d0c4aee32" />
小程序里的配置也抓上配好了，能获取部分信息，账单信息无法获取。

2026-08-24 11:14:41.320 ERROR (MainThread) [custom_components.crcgas.sensor] 获取账单列表失败: 'NoneType' object has no attribute 'get'
2026-08-24 11:14:41.425 WARNING (MainThread) [custom_components.crcgas.sensor] 缺少账单信息: bill_ym=, app_no=
2026-08-24 11:14:41.712 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'crcgas' doesn't specify unit_class when calling async_add_external_statistics at custom_components/crcgas/sensor.py, line 407: async_add_external_statistics(hass, gas_metadata, gas_stats). This will stop working in Home Assistant 2026.11, please create a bug report at https://github.com/C3H3-AI/ha-crcgas/issues
2026-08-24 11:14:41.740 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'crcgas' doesn't specify unit_class when calling async_add_external_statistics at custom_components/crcgas/sensor.py, line 432: async_add_external_statistics(hass, bill_metadata, bill_stats). This will stop working in Home Assistant 2026.11, please create a bug report at https://github.com/C3H3-AI/ha-crcgas/issues
2026-08-24 11:14:46.112 WARNING (MainThread) [py_vhome] Stop network_shakehand ... 
2026-08-24 11:14:46.694 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for weather.puyang exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2026-08-24 11:14:51.731 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not determine the power state of the Bluetooth adapter hci0 [B8:27:EB:DE:0E:42] (0) due to timeout after 5 seconds
2026-08-24 11:14:52.372 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for weather.puyang exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2026-08-24 11:15:10.056 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for weather.puyang exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

2026-08-24 11:25:11.026 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for weather.puyang exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2026-08-24 11:26:10.992 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for weather.puyang exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2026-08-24 11:28:51.290 ERROR (MainThread) [custom_components.crcgas.sensor] 获取账单列表失败: 'NoneType' object has no attribute 'get'
2026-08-24 11:28:51.382 WARNING (MainThread) [custom_components.crcgas.sensor] 缺少账单信息: bill_ym=, app_no=
2026-08-24 11:29:39.833 INFO (MainThread) [custom_components.crcgas.button] 用户触发: 手动刷新数据
2026-08-24 11:29:39.835 DEBUG (MainThread) [custom_components.crcgas.api] 请求: POST https://wmp-svc.crcgas.com/wmp-wechat-rest/mp/pay/queryArrears
2026-08-24 11:29:40.153 DEBUG (MainThread) [custom_components.crcgas.api] 请求: GET https://wmp-svc.crcgas.com/wmp-wechat-rest/mp/pay/queryPayHistory
2026-08-24 11:29:40.277 DEBUG (MainThread) [custom_components.crcgas.api] 请求: GET https://wmp-svc.crcgas.com/wmp-wechat-rest/bill/getGasBillList
2026-08-24 11:29:40.464 ERROR (MainThread) [custom_components.crcgas.sensor] 获取账单列表失败: 'NoneType' object has no attribute 'get'
2026-08-24 11:29:40.465 DEBUG (MainThread) [custom_components.crcgas.api] 请求: GET https://wmp-svc.crcgas.com/wmp-wechat-rest/bill/getGasBillList4Chart
2026-08-24 11:29:40.627 WARNING (MainThread) [custom_components.crcgas.sensor] 缺少账单信息: bill_ym=, app_no=
2026-08-24 11:29:40.627 DEBUG (MainThread) [custom_components.crcgas.api] 请求: GET https://wmp-svc.crcgas.com/wmp-wechat-rest/binding/getMpBindingCons
2026-08-24 11:29:40.704 INFO (MainThread) [custom_components.crcgas.history_storage] 已加载历史数据: 0 条用气记录
2026-08-24 11:29:40.705 INFO (MainThread) [custom_components.crcgas.sensor] 数据更新完成: 欠费¥0.0, 读数0, 状态=normal
2026-08-24 11:29:40.706 DEBUG (MainThread) [custom_components.crcgas.sensor] Finished fetching crcgas data in 0.871 seconds (success: True)
2026-08-24 11:30:11.010 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for weather.puyang exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

**Comment by happyhack123** [comment]
<img width="581" height="613" alt="Image" src="https://github.com/user-attachments/assets/a2d8e53a-3ba8-49f6-a84d-4e91168c0bec" />一样 账单数据不对   wx页面能够显示具体的金额  但是集成没有  应该是接口数据定义的时候弄错了
